### ISSUE TITLE
Suggestion: check file extension

### ISSUE THREAD

**Issue by jasjuang** [richq/cmake-lint#10]
Would it be possible to check whether the file is cmake related file such as ".cmake" or "CMakeLists.txt" before running the script?

cpplint has a similar function that checks whether the file is ".cpp" or ".h" etc. Would be great to see it on cmakelint as well.

Thanks in advance to whoever knows python well that helps!

**Comment by richq** [comment]
I actually implemented this right at the start and completely forgot! When you run it on some random file it tells you that it is ignoring it:

    $ cmakelint README.md
    Ignoring file: README.md
    Total Errors: 0

Feel free to reopen the issue if you spot bugs in this, but it seems to work as intended.

**Comment by jasjuang** [comment]
Oops my bad. Thanks for the reply!
