### ISSUE TITLE
Exiting as success even when there is error (pip install needs update)

### ISSUE THREAD

**Issue by jasjuang** [richq/cmake-lint#12]
cmakelint CMakeLists.txt

CMakeLists.txt:2: Extra spaces between 'project' and its () [whitespace/extra]
Total Errors: 1

echo $?
0

I think there might be a bug because it is exiting with a success (0) even if there is error. Could you look into this?

EDIT: It is working correctly for the current repo, but not the pip install version. Could you update the pip install version? 

Thanks

**Comment by richq** [comment]
There's been a bit of a logistical oversight here as I was not involved setting up the PyPi package. @tkruse created it after seeing my github repository. I'll see if I can sort it out somehow.

**Comment by tkruse** [comment]
Hi, yes, I did not track progress of cmake-lint, so pip version is still 1.2.01, while 1.3.3 is out. I could push 1.3.3 to pipy, unless Richard wants to take over that part and publish himself.

**Comment by richq** [comment]
Oh, that's great. Can you push 1.3.3? I don't have any great desire to take over (more work for me!) - Thibault, would it be super annoying if I just pinged you each release? There aren't that many.

**Comment by jasjuang** [comment]
Thanks richq and tkruse. It is working great now

**Comment by tkruse** [comment]
Richard, sorry I screwed up a bit. I thought my upload of 1.3.3 was corrupted, so I deleted and now I cannot upload a fixed 1.3.3 (pypi does not allow, to prevent malicious attacks be replacing versions).
So I need a new version number, like 1.3.4 or 1.3.3.1 to properly push the last changes. do you have a preference?

I am not sure whether pinging me would be more or less work than running `python setup.py sdist upload`, but it's no trouble for me if you ping me.

**Comment by richq** [comment]
I've added a new commit + tag for 1.3.3.1.

**Comment by tkruse** [comment]
Thanks, it's on pipy. Sorry for the trouble.
