### ISSUE TITLE
End paran should be level up in mismatches spaces count

### ISSUE THREAD

**Issue by HenryMiller1** [richq/cmake-lint#13]
Consider the following cmake code.

    IF(SOMEBOOL)
      FIND_LIBRARY(MYLIBRARY
        NAMES foo bar.so
        PATHS /usr/local/lib
      )
    ENDIF()

This fails on the closing parentheses since the white space at the beginning of the line doesn’t match the lack of space at the beginning parentheses at the FIND_LIBRARY statement. I’m forced to do this, which seems less readable in long blocks.

    IF(SOMEBOOL)
      FIND_LIBRARY(MYLIBRARY
        NAMES foo bar.so
        PATHS /usr/local/lib)
    ENDIF()

**Comment by richq** [comment]
Yes you're right, they are both very valid styles. I'll see about making this improvement.

**Comment by richq** [comment]
This should be fixed in 1.3.4.
