### ISSUE TITLE
can not exceute cmakelint file on windows 10

### ISSUE THREAD

**Issue by kesco** [richq/cmake-lint#15]
I try to use cmaelint with the SublimeLinter-contrib-cmakelint in sublime text 3 on windows 10. But I can not exceute the cmakelint file directly. Using `python cmakelint` command  is ok.

**Comment by richq** [comment]
Not much I can do about this.

**Comment by jasjuang** [comment]
Hey I am the author of SublimeLinter-contrib-cmakelint, recently upgraded to windows 10 and encountered the same issue.

The best way to fix it is if @richq can provide a cmakelint.exe and include it in the python pip package just like cpplint.

Currently windows 10 cannot recognize "cmakelint" as a executable file, therefore a full path to "cmakelint" has to be specified. I pushed a temporary fix where I hard coded the full path on windows to C:\Python27\Scripts\cmakelint. It works for now so feel free to pull it.

I attempted to get the python path by
``````
>>> import os
>>> import sys
>>> os.path.dirname(sys.executable)+'\Scripts\cmakelint'
``````
but it doesn't work because sublime is using it's own python instead of the system python, so  os.path.dirname(sys.executable) returns nothing.

**Comment by richq** [comment]
> The best way to fix it is if @richq can provide a cmakelint.exe and include it in the python pip package just like what the author of cpplint did.

https://pypi.python.org/pypi/cpplint ? I don't see any exe, but the page could filter by browser or something. Also I have no idea what an exe would contain. It all sounds like more work, and as I use neither Windows nor Sublime I have no particular wish to do anything extra ;-)

**Comment by tkruse** [comment]
I guess setuptools can additionally create a windows exe when using the target `bdist_wininst`
That would be the job of the one creating releases (me, currently).
See:
https://pythonhosted.org/an_example_pypi_project/setuptools.html

**Comment by jasjuang** [comment]
@tkruse It would be super awesome if you can make it happen. Let me know when you are done so I can update my code to reflect the change as well!

**Comment by tkruse** [comment]
doing so requires running the setup from windows, whereas I was only working on linux so far, so I will need to find time to set up python on windows.

**Comment by jasjuang** [comment]
If you are having trouble getting hold of a windows machine let me know, I can open up a temporary Windows EC2 instance with Python installed for you.

**Comment by tkruse** [comment]
version 1.3.4 should now have a windows installer on pypi, give it a shot.

**Comment by jasjuang** [comment]
I tried but it didn't work. Sorry I should've clarified. A separate exe installer is not what is missing. What is missing is a python script converted executable. We want to be able to open the terminal and type

cmakelint.exe CMakeLists.txt

and it works as if in the linux world like

cmakelint CMakeLists.txt

I attach a screenshot on how cpplint does it. It installs a cpplint-script.py and cpplint.exe to C:\Python27\Scripts

![screenshot from 2016-04-11 14 07 45](https://cloud.githubusercontent.com/assets/11759200/14442685/ed3eefee-ffef-11e5-92ad-b6532b008295.png)

**Comment by tkruse** [comment]
my bad, i did not read well enough. So I guess I have to follow these instructions:
https://pythonhosted.org/setuptools/setuptools.html#automatic-script-creation
Just did so using this:
```
 entry_points={
          'console_scripts': [
              'cmakelint = cmakelint.main:main'
          ]
      },
```
Can you try again?

**Comment by jasjuang** [comment]
Could you remove the old version? pip install cmakelint is still grabbing
the old one (ends with tar.gz) instead of the new one (ends with zip).

**Comment by tkruse** [comment]
I cannot, because pypi forbids to change released files (https://github.com/pypa/packaging-problems/issues/74). 
All we can do then is to create a new release for that setup.py. @richq, do you want to merge #18 and increase the version, maybe to 1.3.4.1?

**Comment by richq** [comment]
How could I say no? Merged and I've bumped the version number. I'll tag it later tonight, but master only has 2 unreleased changes that are harmless enough (this one and the licence file addition). Thanks for sorting this out.

**Comment by tkruse** [comment]
ok, 1.3.4.1 is on pypi, hope this one is golden.

**Comment by jasjuang** [comment]
Verified it works on both Windows and Linux. Thanks @tkruse and @richq for the effort!
