### ISSUE TITLE
readability/mixedcase: False positive in CHECK_C_SOURCE_COMPILES

### ISSUE THREAD

**Issue by hholzgra** [richq/cmake-lint#2]
the check triggers on the pthread_once() call within the test code passed as argument to  CHECK_C_SOURCE_COMPILES:

 CHECK_C_SOURCE_COMPILES("
    #include <pthread.h>
    void foo(void) {}
    int main()
    {
      pthread_once_t once_control = PTHREAD_ONCE_INIT;
      pthread_once(&once_control, foo);
      return 0;
    }"
    HAVE_PTHREAD_ONCE_INIT
  )

**Comment by richq** [comment]
Should be fixed in cc06f8a00fcd195e7fa9e1f35c5781de0259e8fd - and it took less than 2 years!
