### ISSUE TITLE
Exit with 1 on finding errors

### ISSUE THREAD

**Issue by smspillaz** [richq/cmake-lint#7]
Currently cmakelint exits with 0 on both success and failure. Life would be a lot easier for scripts if cmakelint existed with 1 when it found errors.

**Comment by richq** [comment]
Oh this is a good plan, thanks!

**Comment by smspillaz** [comment]
Thanks!

Do you think you could roll a new release with this fix too? I'll be able to drop a workaround I'm using in my scripts once that's done.

**Comment by richq** [comment]
Sure, I've tagged 1.3.2 with this change.
